#!/usr/bin/env python3
"""Regenerate the Writing section of index.html from the Hashnode RSS feed.

Build-time injection rather than a client-side fetch, because:
  - GitHub Pages is static, and Hashnode sends no CORS header, so a browser
    fetch() from sukalyan2003.github.io would be blocked outright.
  - Rendering server-side keeps the posts in the HTML for crawlers and for
    readers with JS disabled.

Standard library only, so CI needs no pip install.

Usage:
    python3 scripts/update_writing.py            # rewrite index.html in place
    python3 scripts/update_writing.py --check    # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import html
import re
import sys
import urllib.error
import urllib.request
from email.utils import parsedate_to_datetime
from pathlib import Path

FEED_URL = "https://sukalyanroy.hashnode.dev/rss.xml"
BLOG_URL = "https://sukalyanroy.hashnode.dev/"
TARGET = Path(__file__).resolve().parent.parent / "index.html"

START = "<!-- WRITING:START (generated by scripts/update_writing.py - do not edit by hand) -->"
END = "<!-- WRITING:END -->"

POST_COUNT = 3
SUMMARY_CHARS = 165
MAX_TAGS = 2
# Hashnode sits behind Cloudflare and 403s the default urllib agent.
USER_AGENT = "Mozilla/5.0 (compatible; sukalyan2003.github.io writing-sync)"


def fetch_feed(url: str | None = None) -> str:
    request = urllib.request.Request(
        url or FEED_URL, headers={"User-Agent": USER_AGENT}
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        if response.status != 200:
            raise RuntimeError(f"feed returned HTTP {response.status}")
        return response.read().decode("utf-8", errors="replace")


def _tag(item: str, name: str) -> str:
    """Pull one element's text, CDATA-wrapped or not."""
    match = re.search(
        rf"<{name}>\s*(?:<!\[CDATA\[)?(.*?)(?:\]\]>)?\s*</{name}>", item, re.S
    )
    return match.group(1).strip() if match else ""


def _strip_markup(text: str) -> str:
    text = re.sub(r"<[^>]+>", " ", text)
    return re.sub(r"\s+", " ", html.unescape(text)).strip()


def _summarize(text: str, limit: int = SUMMARY_CHARS) -> str:
    text = _strip_markup(text)
    if len(text) <= limit:
        return text
    clipped = text[:limit]
    # Prefer a sentence end, then a word boundary, so we never cut mid-word.
    sentence = max(clipped.rfind(". "), clipped.rfind("? "), clipped.rfind("! "))
    if sentence > limit * 0.55:
        return clipped[: sentence + 1]
    space = clipped.rfind(" ")
    return (clipped[:space] if space > 0 else clipped).rstrip(",;:-") + "…"


def parse_posts(feed: str, count: int = POST_COUNT) -> list[dict]:
    posts = []
    for raw in re.findall(r"<item>(.*?)</item>", feed, re.S)[:count]:
        link = _tag(raw, "link")
        title = _strip_markup(_tag(raw, "title"))
        if not link or not title:
            continue
        published = parsedate_to_datetime(_tag(raw, "pubDate"))
        summary = _summarize(_tag(raw, "description") or _tag(raw, "content:encoded"))
        tags = [
            _strip_markup(t)
            for t in re.findall(
                r"<category>\s*(?:<!\[CDATA\[)?(.*?)(?:\]\]>)?\s*</category>", raw, re.S
            )
        ]
        posts.append(
            {
                "title": title,
                "link": link,
                "summary": summary,
                # %-d is not portable to Windows, so strip the zero by hand.
                "date_label": f"{published.day} {published:%B %Y}",
                "datetime": f"{published:%Y-%m-%d}",
                "tags": [t for t in tags if t][:MAX_TAGS],
            }
        )
    if not posts:
        raise RuntimeError("no items parsed from feed")
    return posts


def render(posts: list[dict]) -> str:
    esc = lambda value: html.escape(value, quote=True)  # noqa: E731
    cards = []
    for post in posts:
        tags = "".join(
            f"<span>{esc(tag)}</span>" for tag in post["tags"]
        )
        tag_block = (
            f'\n                <div class="writing-tags" aria-label="Topics">{tags}</div>'
            if tags
            else ""
        )
        cards.append(
            f"""              <article class="writing-card">
                <time class="writing-date" datetime="{esc(post['datetime'])}">{esc(post['date_label'])}</time>
                <h3><a href="{esc(post['link'])}" target="_blank" rel="noopener">{esc(post['title'])}</a></h3>
                <p>{esc(post['summary'])}</p>{tag_block}
                <div class="writing-more">
                  <a href="{esc(post['link'])}" target="_blank" rel="noopener">Read post</a>
                </div>
              </article>"""
        )
    return (
        f"{START}\n"
        f'            <div class="writing-grid mt-4">\n'
        + "\n\n".join(cards)
        + "\n            </div>\n"
        f'            <p class="text-center mt-4 mb-0">\n'
        f'              <a class="btn btn-outline-primary" href="{BLOG_URL}" target="_blank" rel="noopener">All posts on Engineering Tales</a>\n'
        f"            </p>\n"
        f"            {END}"
    )


def splice(document: str, block: str) -> str:
    start, end = document.find(START), document.find(END)
    if start == -1 or end == -1:
        raise RuntimeError(f"markers not found in {TARGET.name}")
    return document[:start] + block + document[end + len(END):]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report whether the file is stale without writing it",
    )
    args = parser.parse_args()

    try:
        posts = parse_posts(fetch_feed())
    except (urllib.error.URLError, RuntimeError, ValueError) as exc:
        # Leave the committed section untouched rather than blanking it.
        print(f"error: could not refresh writing section: {exc}", file=sys.stderr)
        return 2

    current = TARGET.read_text(encoding="utf-8")
    updated = splice(current, render(posts))

    for post in posts:
        print(f"  {post['date_label']:<18} {post['title']}")

    if updated == current:
        print("writing section already up to date")
        return 0

    if args.check:
        print("writing section is STALE", file=sys.stderr)
        return 1

    TARGET.write_text(updated, encoding="utf-8")
    print(f"updated {TARGET.name} with {len(posts)} posts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
