#!/usr/bin/env python3
"""Regenerate section 04 (From the blog) in index.html from the local blog.

The posts live in content/blog/ and are built to /blog/ by build_blog.py,
which also calls this module. The latest posts are read from the generated
blog/search.json, so this file needs only the standard library.

Build-time injection rather than a client-side fetch keeps the posts in the
HTML for crawlers and for readers with JavaScript disabled, which the design
requires.

Usage:
    python3 scripts/update_writing.py            # rewrite index.html in place
    python3 scripts/update_writing.py --check    # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "index.html"
SEARCH_INDEX = ROOT / "blog" / "search.json"

START = "<!-- WRITING:START (generated by scripts/update_writing.py - do not edit by hand) -->"
END = "<!-- WRITING:END -->"

POST_COUNT = 4
SUMMARY_CHARS = 180
MAX_TAGS = 2


def _strip_markup(text: str) -> str:
    text = re.sub(r"<[^>]+>", " ", text)
    return re.sub(r"\s+", " ", html.unescape(text)).strip()


def _summarize(text: str, limit: int = SUMMARY_CHARS) -> str:
    text = _strip_markup(text)
    text = re.sub(r"^TL;?DR:?\s*", "", text, flags=re.I)
    if len(text) <= limit:
        return text
    clipped = text[:limit]
    sentence = max(clipped.rfind(". "), clipped.rfind("? "), clipped.rfind("! "))
    if sentence > limit * 0.55:
        return clipped[: sentence + 1]
    space = clipped.rfind(" ")
    return (clipped[:space] if space > 0 else clipped).rstrip(",;:-") + "…"


def posts_from_records(records: list[dict], count: int = POST_COUNT) -> list[dict]:
    """Newest posts from blog/search.json, shaped for render()."""
    ordered = sorted(records, key=lambda r: r["date"], reverse=True)[:count]
    if not ordered:
        raise RuntimeError("no posts in the blog index")
    return [
        {
            "title": r["title"],
            "link": r["url"].lstrip("/"),  # relative to the homepage
            "summary": _summarize(r.get("summary", "")),
            "date_label": r["dateLabel"],
            "datetime": r["date"][:10],
            "tags": [t["label"] for t in r.get("tags", [])][:MAX_TAGS],
        }
        for r in ordered
    ]


def render(posts: list[dict]) -> str:
    def esc(value: str) -> str:
        return html.escape(value, quote=True)

    items = []
    for post in posts:
        tags = "".join(f'<span class="tag">{esc(t)}</span>' for t in post["tags"])
        tag_block = f'\n            <div class="tags">{tags}</div>' if tags else ""
        summary = f"\n            <p>{esc(post['summary'])}</p>" if post["summary"] else ""
        items.append(
            f"""        <article class="dispatch">
          <div class="dispatch__date">
            <time datetime="{esc(post['datetime'])}">{esc(post['date_label'])}</time>
          </div>
          <div>
            <h3><a href="{esc(post['link'])}">{esc(post['title'])}</a></h3>{summary}
            <div class="dispatch__meta">{tag_block}
              <a class="more" href="{esc(post['link'])}">Read</a>
            </div>
          </div>
        </article>"""
        )

    return (
        f"{START}\n"
        f'      <div class="dispatches">\n'
        + "\n\n".join(items)
        + f"\n      </div>\n      {END}"
    )


def splice(document: str, block: str) -> str:
    start, end = document.find(START), document.find(END)
    if start == -1 or end == -1:
        raise RuntimeError(f"markers not found in {TARGET.name}")
    return document[:start] + block + document[end + len(END):]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report whether the file is stale without writing it",
    )
    args = parser.parse_args()

    try:
        posts = posts_from_records(json.loads(SEARCH_INDEX.read_text(encoding="utf-8")))
    except (OSError, ValueError, KeyError, RuntimeError) as exc:
        # Leave the committed section untouched rather than blanking it.
        print(f"error: could not refresh dispatches (run build_blog.py first): {exc}", file=sys.stderr)
        return 2

    current = TARGET.read_text(encoding="utf-8")
    updated = splice(current, render(posts))

    for post in posts:
        print(f"  {post['date_label']:<14} {post['title']}")

    if updated == current:
        print("dispatches already up to date")
        return 0

    if args.check:
        print("dispatches are STALE", file=sys.stderr)
        return 1

    TARGET.write_text(updated, encoding="utf-8")
    print(f"updated {TARGET.name} with {len(posts)} dispatches")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
